In [1]:
import numpy as np

In [ ]:
#!pip install numpy

# Numpy (NumericPython)

Pythonda matematiksel işlemleri hızlı bir biçimde yapabilmemizi sağlayan kütüphane

In [5]:
p_list = list(range(1_000_000)) #Klasik python listesi
np_array = np.array(p_list) # 1m elemanı olan np array.

In [8]:
%%timeit
[x+1 for x in p_list]

29.3 ms ± 962 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
%%timeit
np_array + 1

1.1 ms ± 6.99 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [10]:
arr1 = np.array(1)

In [12]:
type(arr1) # ndarray -> n-dimensional array

numpy.ndarray

In [14]:
arr1.ndim # ndim -> ndimension(boyutu) -> 0

0

In [19]:
arr2 = np.array([  10, 20, 30 ])
arr2.ndim, arr2.shape # 1D Array (Vector)

(1, (3,))

In [20]:
arr3 = np.array([ 40, 50, 60])
arr3.ndim,arr3.shape

(1, (3,))

In [21]:
result = arr2+arr3
result

array([50, 70, 90])

In [22]:
result2 = arr3-arr2
result2

array([30, 30, 30])

In [25]:
arr4 = np.array([ 100,200 ])
arr3*arr4 #Shape uyuşmazlığı olması durumunda matematiksel işlemler yapılamaz.

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [26]:
arr5 = np.array(
    [
        [10,20,30],
        [40,50,60]
    ]
)
# 2 boyutlu , 2,3 şekilli bir matris.
arr5.ndim, arr5.shape

(2, (2, 3))

In [27]:
arr6 = np.array(
    [
        [70, 80, 90],
        [100, 110, 120]
    ]
)
arr6.ndim, arr6.shape

(2, (2, 3))

In [28]:
result = arr5+arr6
result

array([[ 80, 100, 120],
       [140, 160, 180]])

# Dot Product (İç Çarpım)

In [29]:
np.dot(arr5,arr6)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [30]:
arr7 = np.array([
    [10,20,30],
    [40,50,60]
])

arr8 = np.array(
    [
        [10,20],
        [30,40],
        [50,60]
    ]
)
arr7.shape, arr8.shape
#Dot Product -> İlk matrisin sütun sayısı, ikinci matrisin satır sayısına eşit olmalı.

((2, 3), (3, 2))

In [31]:
np.dot(arr7,arr8)

array([[2200, 2800],
       [4900, 6400]])